### PR TITLE
Add PTC support in UI

### PR DESCRIPTION
**Pull request by blockmurder**
Hi Martin
Finally I'm on the sailing yacht where the Pactor is set up and I found some time to get the system up and running. Fixed the PTC selection during the the process (#133).

### CODE REVIEW

**Comment by martinhpedersen** [comment]
Thanks for the two PRs @blockmurder.

Sorry that I have not been able to review and merge yet. I've been swamped with both work and personal matters these past couple of months, but I hope that things will settle soon. I will get back to you asap.

73s

**Comment by martinhpedersen** [comment]
@blockmurder - Do you mind removing the `go generate` (go-bindata-assetfs) from of this commit? They will likely produce a merge conflict, so I think it's best to run `go generate` after the merge.

Thanks!

**Comment by martinhpedersen** [comment]
Also, I see that you've used "Pactor" as the label for ptc. I'm afraid that it might be misleading, since PTC is a line of pactor modems(??). Or maybe `ptc://` should be changed to `pactor://`? What do you think?

I would like to invite @harenber to join in on this discussion, since he was the one that picked `ptc://` for the driver scheme.

**Comment by harenber** [comment]
As all the other schemes are named after the protocol in use, I think changing it from ptc:// to pactor:// would be the natural choice. I will try to do that...

**Comment by harenber** [comment]
@martinhpedersen  Done :-) https://github.com/harenber/ptc-go/issues/12

**Comment by blockmurder** [comment]
@martinhpedersen Done, sorry for the delay!

**Comment by martinhpedersen** [comment]
Changes manually cherry-picked into `feature/ptc-support` and `develop`.

**Pull request closed without merging**
