### PR TITLE
Improve results of message 'reply' and 'forward' buttons

### PR DESCRIPTION
**Pull request by DougCollinge**
Make 'reply' open the form with two blank lines followed by the quoted reply
text, and position the text input cursor at the top, same as other email clients.
Make 'forward' fill the form with the quoted text, no blank lines, and clear 
and put the text input cursor into the 'To' field, since you are presumably 
forwarding it to someone else.

### CODE REVIEW

**Review by martinhpedersen — APPROVED** [review]
This is excellent Doug 👍 

Do you mind adding yourself to the Contributors list in `README.md`? You can just do it as a secondary commit on this branch. Thanks!

**Comment by DougCollinge** [comment]
Ok, It seems I forgot to push a commit but it's done now. I'm still fumbling with git so I didn't have the courage to attempt to squash those two commits together.

And I added myself to the README - thanks! It's such a small contribution...

**Review by martinhpedersen — CHANGES_REQUESTED** [review]
Thanks 👍 

Despite being small changes, these little details are great contributions. And as an added bonus, small PRs are very easy to review and merge 🙂 

The `.gitignore` changes should be omitted though, especially `bindata_assetfs.go` which is an important file that should not be ignore by git. The pat executable should probably be in gitignore, but I'd prefer to keep PRs as specific as possible to make them easier to review.

If you prefer, I can fix this for you by cherry-picking all but the first commit. But it's a nice opportunity for you to improve your [git rebase](https://medium.com/@daendersby/til-git-rebasing-removing-rage-commits-4b5c42e7af3a) skills 🙂 

Thanks again!

**Comment by DougCollinge** [comment]
Thanks for the opportunity to improve! Here's an update with the changes you requested. (I think)

**Review by martinhpedersen — CHANGES_REQUESTED** [review]
Hmm.. it seems like you updated your branch, and then merged in the old version. So this branch now contains 7 commits, but should really only contain two.

After rebasing your branch, you need to do a "force push" to github. I suspect you attempted a normal push, got an error, pulled and then pushed again.

1. Do an interactive rebase and drop all but the two relevant commits (80548621d0b115ae7fb6e274c08f5ffb2b072346 and de4d22edcf0ab68e4627378057c188b3916121da).
2. `git push -f`

😄

**Comment by martinhpedersen** [comment]
... alternativly you could start with a clean branch of `develop` and cherry-pick the relevant commits. But the interactive rebase is very powerful, so I would focus on learning that 🙂

**Review by martinhpedersen — APPROVED** [review]
Perfect! Thank you 😊

**Pull request merged**
