### PR TITLE
Implement new initialisation call from refactored pactor driver

### PR DESCRIPTION
**Pull request by blockmurder**
After rewriting the pactor driver taking suggestions harenber/ptc-go#7 into account, the initialisation procedure has changed.

### CODE REVIEW

**Comment by martinhpedersen** [comment]
Wow! Didn't expect you to implement the suggested API within hours 😁 

Judging from the output of Travis, it looks like you'll also need to update the submodule (vendor/githuh.com/harenber/ptc-go) to commit 58ceb41d871c6d54edd3c72b4dcc7334fcf519f7 (I guess?).

```bash
cd vendor/github.com/harenber/ptc-go/
git fetch && git checkout 58ceb41d871c6d54edd3c72b4dcc7334fcf519f7
cd -
git add vendor/github.com/harenber/ptc-go
```

```
diff --git a/vendor/github.com/harenber/ptc-go b/vendor/github.com/harenber/ptc-go
index 9ff09d2..58ceb41 160000
--- a/vendor/github.com/harenber/ptc-go
+++ b/vendor/github.com/harenber/ptc-go
@@ -1 +1 @@
-Subproject commit 9ff09d27c2ed48127d5ef1082f0f0a946a7968bb
+Subproject commit 58ceb41d871c6d54edd3c72b4dcc7334fcf519f7
```

Could you fix that as well, so I'm sure I update to the correct version?

Thanks!

**Comment by blockmurder** [comment]
Just found another bug, hope to have a fix ready this evening...

**Comment by blockmurder** [comment]
@martinhpedersen I think the new driver is stable enought to be merged into the develop branch. Looking forward for feedback from other Pactor users!

**Comment by sv1uy** [comment]
Great,

I am interested in trying PACTOR. Please let us know when a compiled
version of PAT which includes PACTOR will be available.
I can test with a PTC-II and with a P4dragon.

---
73 de Demetre - M0SUY/SV1UY

**Comment by martinhpedersen** [comment]
Thanks @blockmurder. I'll hope to review and merge tomorrow or friday.
I'd love to have you and Torsten listed in as [contributors](https://github.com/la5nta/pat/blob/master/README.md#contributors-alphabetical). If you don't mind, could you push a commit adding both of you? (It's probably best to ask Torsten for permission first).

I appreciate all the efforts!

**Comment by martinhpedersen** [comment]
@sv1uy, PACTOR (PTC-II and PTC-III) support is was released with v0.7.0 a couple of days ago. This PR includes some improvements, but you can already test the pactor support by downloading the [latest released binaries](https://github.com/la5nta/pat/releases/tag/v0.7.0). 73!

**Comment by guitarpicva** [comment]
A second thank you.  It has been fun watching you guys crank it out.  I am learning a bit more git also. ;)

⁣Get TypeApp for Android ​

**Comment by blockmurder** [comment]
@martinhpedersen Done ;-)

**Comment by martinhpedersen** [comment]
@blockmurder - I will merge this now, but noticed one thing:

Previously if the user is missing pactor config in `config.json` due to old installation, the package defaulted to use `"/dev/ttyUSB0"`. Now it defaults to `""`.

I'm guessing you'd rather prefer that we default to the values from `cfg.DefaultConfig`. I will fix it after the merge :)

**Pull request merged**
