### PR TITLE
Web GUI: Add custom sorting of message table headers

### LINKED ISSUE #154: Web Gui - Allow column sorting
It would be nice to be able to sort on any of the columns in inbox, outbox, sent, date.

### PR DESCRIPTION
**Pull request by xylo04**
Martin, let me know if you want to change these supporting changes. They're not strictly necessary but I think they make sense.

* Remove bindata_assetfs.go from the repo and always have the build process generate it
* Ignore IDE files

Fixes #154

### CODE REVIEW

**Comment by xylo04** [comment]
AppVeyor failed because of my `make.bash` changes, I was a little worried that CI wouldn't do well. I'll try to fix that up before abandoning that part of the change.

**Comment by martinhpedersen** [comment]
Thanks for contributing Chris :)

We need to keep `bindata_assetfs.go` in the repo in order to support quick install via `go get`. So I would appreciate it if you could revert those changes (and `amend`/`squash`). I'll run `go generate` to update bindata_assetfs after the merge.

Thank you!

**Comment by martinhpedersen** [comment]
Please consider adding yourself to the contributors list (preferably as a separate commit): https://github.com/la5nta/pat/blob/master/README.md#contributors-alphabetical

👍

**Comment by xylo04** [comment]
Acknowledged. I prefer leaving generated source out of the repo, but preserving `go get` compatibility is a good reason to break that rule.

I'd still like to add `go-bindata-assetfs [-debug] res/...` to either `make.bash` or documentation because that was not obvious, but it's not integral to this PR.

Will send a separate PR adding to `CONTRIBUTORS.md`.

**Comment by martinhpedersen** [comment]
> I'd still like to add go-bindata-assetfs [-debug] res/... to either make.bash or documentation because that was not obvious, but it's not integral to this PR.

Sure, I agree. I've been meaning to add it to the documentation for a long time, or even better to add a new wiki page describing how to hack on the project. Sorry about that!

New issue on this topic: https://github.com/la5nta/pat/issues/175

-------

Regarding the PR,

The sorting works great, even with my big inbox of ~2300 messages. So thank you very much for this!

If you ever feel like contributing more, please don't hesitate to contact me or send more PRs. It's great to have someone as experiences as you working on the gui. I have a few ideas, but as you might have guessed I don't have much experience with js and web development in general.

I will merge this to `develop` and include it in the next release :-)

**Comment by martinhpedersen** [comment]
Note to self: Remember to `go generate` before merging to master.

**Comment by martinhpedersen** [comment]
rebased and merged to `master`. Thanks @xylo04 :)

**Pull request closed without merging**
