### PR TITLE
Support for Distance and Azimuth in rmslist (Fixes #4)

### LINKED ISSUE #4: Display distance to node in rmslist
_From @martinhpedersen on October 14, 2015 10:10_

Need a way to calculate distance between maidenhead locators for this.

_Copied from original issue: la5nta/wl2k-go#14_

### PR DESCRIPTION
**Pull request by jc-m**
For feadback - Not ready for merge - I want to add sorting based on distance.

### CODE REVIEW

**Comment by martinhpedersen** [comment]
Hi @jc-m,

thank you for getting involved. This is definitely a feature that should be included in Pat.

The implementation looks good to me, but I would prefer not changing the signature of `Command.HandleFunc` just now.

I realize that we should (at some point) move away from using global variables in `package main`, but I would rather we'd do that in a separate commit some time in the future. For now, I would prefer that you access the user's gridsquare through the global `config.Locator` variable please.

Regarding sort by distance - I think that would be a great addition to this PR :-)

Thank you!

**Comment by martinhpedersen** [comment]
It seem like you forgot to include vendor/github.com/pd0mz in the last push.

I don't know the proper procedure to fix this, but I believe this may help:

```bash
rm -rf .git/modules/vendor/github.com/pd0mz
git submodule add https://github.com/pd0mz/go-maidenhead.git vendor/github.com/pd0mz/go-maidenhead
git commit --amend
```

**Comment by jc-m** [comment]
this is ready to merge

**Comment by martinhpedersen** [comment]
Thank you so much @jc-m, it looks very good :+1: 

Do you mind adding yourself to the contributors list in README.md?

I really appreciate the contribution!

**Comment by jc-m** [comment]
done ! thanks.

**Comment by martinhpedersen** [comment]
Thank you!

Closes #4

**Pull request merged**
