### PR TITLE
web: Add all the ax25 transports to the transport menu

### PR DESCRIPTION
**Pull request by cminyard**
So they can be individually selected and used from the web page.

### CODE REVIEW

**Review by martinhpedersen — APPROVED** [review]
Thanks! I forgot about this 🙂 

I'm a bit concerned that novice users may find it confusing when they are prompted with this many different ax25 options.

So i'd like to make a few adjustments:
* Move the `ax25+...` options to a separate option group labeled "advanced".
* Remove the legacy serial-tnc option (same as the new ax25+serial-tnc).

**Comment by martinhpedersen** [comment]
Something like this:

image

**Comment by cminyard** [comment]
On Sun, May 21, 2023 at 02:34:50AM -0700, Martin Hebnes Pedersen wrote:
> Something like this:
> 
> image

Yes, that's better.  Thanks.

**Comment by martinhpedersen** [comment]
Thank you 😊

**Pull request merged**
