### PR TITLE
Bump dependency versions

### PR DESCRIPTION
**Pull request by xylo04**
No strong motivation, just housekeeping.

This is simply:

```
go get -u
go mod tidy
```

Plus bumping the golang version.

### CODE REVIEW

**Comment by xylo04** [comment]
Weird, Travis CI is failing on Darwin with
 
```
$ GO111MODULE=on go vet ./...
# github.com/albenik/go-serial/v2
../../../../pkg/mod/github.com/albenik/go-serial/v2@v2.0.0/zsyscall_darwin.go:16:27: undefined: unix.SYS_IOCTL
The command "GO111MODULE=on go vet ./..." exited with 2.
```

That points toward https://github.com/albenik/go-serial, but that version wasn't affected, nor was the module pulling it in, https://github.com/harenber/ptc-go. That doesn't seem like it could be a fluke, but I don't know how this passed before.

**Comment by xylo04** [comment]
Looks similar to https://github.com/ory/dockertest/issues/212

**Comment by martinhpedersen** [comment]
Thanks for digging into this @xylo04 👍 

Waiting for a bit to see if https://github.com/albenik/go-serial/issues/15 gets resolved.

**Comment by xylo04** [comment]
After some local experimentation, I think https://github.com/albenik/go-serial/pull/17 (plus upgrading in ptc-go) will solve this for Pat.

**Comment by xylo04** [comment]
@martinhpedersen albenik/go-serial#17 is merged; this PR is ready for another look.

**Review by martinhpedersen — CHANGES_REQUESTED** [review]
Thank you for resolving the go-serial issue, Chris 👍 

Do you mind squashing these changes into a single commit? Also, please keep the required go version at 1.11, as we aim to support older versions of Go.

Thanks!

**Comment by xylo04** [comment]
Done

**Review by martinhpedersen — APPROVED** [review]
Thank you 😊

**Pull request merged**
