### PR TITLE
Updated to jQuery 3.4.1, Bootstrap 4.4.1

### PR DESCRIPTION
**Pull request by rainerg2000**

### CODE REVIEW

**Comment by rainerg2000** [comment]
done. 
I also removed and .gitignore'd bindata_assetfs.go

**Comment by rainerg2000** [comment]
Oh, without bindata_assetfs.go the build fails. I'm putting it back in.

**Comment by martinhpedersen** [comment]
Yes, bindata_assetfs.go is a bundle of all the files in res/ so we can bundle the assets with the binary. Just leave it unmodified, and I will update it after we have merged all thr required changes to res/ :)

**Comment by rainerg2000** [comment]
sorry for the thrash. Now I'm really done with this PR. Onward to the next one which will add the template support.

**Comment by martinhpedersen** [comment]
I see that the one commit modifies it. If you can update the commit to not modify it, I think we will be ready to merge 👍

Sorry for the confusion, and thank you for the patience :)

**Comment by rainerg2000** [comment]
bindata_assetfs.go now unmodified

**Comment by rainerg2000** [comment]
In a later commit (not yet in this PR) I improved the UX, especially on small screens. Assuming that this version won't go to users anyways, I'd suggest we go through with all of my other  changes, and then polish the UI. It will be much more productive to involve Bootstrap experts then. If we tweak the UX in this version already it will create merge issues for me.

**Comment by martinhpedersen** [comment]
Ah, of course. I understand :) Sorry about that, my bad!

I will do another quick review tomorrow then. I think I'll pull this into a feature branch instead of `develop` for now. Then we can work on the complete feature there, one step at the time. I'll just check some basics in this PR, and then we can move forward with rest as planned.

I'll keep you updated. Thanks again for all of this!

**Comment by martinhpedersen** [comment]
I'm closing this one now, as we're going to continue in another branch (see pr #197).

**Pull request closed without merging**
