### PR TITLE
WIP: Add support for Vara HF

### PR DESCRIPTION
**Pull request by MarSik**
This adds support for Vara HF. I am able to complete a Winlink session with standalone Vara running in wine and PAT talking to it directly.

This depends on https://github.com/n8jja/Pat-Vara/pull/17

Also Radio only mode is not yet propagated properly.

### CODE REVIEW

**Comment by xylo04** [comment]
Thanks for putting this together, but is there a reason to duplicate #280?

**Comment by MarSik** [comment]
Oh, not really, I just did not notice the draft PR in the first place. I was looking for it, but must have overlooked it.

**Comment by MarSik** [comment]
Closed in favor of #280 that is much more complete.

**Comment by xylo04** [comment]
We do need to move #280 forward so thanks for the poke. Martin has some work to do on configurable bandwidths... Oh, I didn't notice he asked for my review on #349, I'd better do that!

**Pull request closed without merging**
