### PR TITLE
Feature/cli forms

### PR DESCRIPTION
**Pull request by rainerg2000**
this PR replaces the #206, and adds the CLI for composing Winlink-style forms messages.

### CODE REVIEW

**Review by martinhpedersen — COMMENTED** [review]
Thanks Rainer :)

I see a number of unrelated changes in `go.mod` and `go.sum`. Running `go mod tidy` removes all of this, but I would appreciate if we could amend the first commit to avoid adding them and then removing them in a later commit. I can fix this if you prefer, just say the word.

I'd also appreciate if you would add yourself to the Contributors list in `README.md` so we have all that settled before merging your code 🎉 

Thanks!

**Comment by rainerg2000** [comment]
Done. I amended as suggested.

**Comment by martinhpedersen** [comment]
Actually I ment amending the first commit, to avoid adding those unrelated changes in the first place 😅

Please excuse my nitpicking, I am just trying to pass on some good practices with regards to maintaining Go projects and keeping a clean and readable git history. Again, I can fix this for you if you prefer 😊

**Comment by rainerg2000** [comment]
please take over and fix this as you prefer. When done, please let me know, so that I can rebase feature/web-forms on it.

**Comment by martinhpedersen** [comment]
Sure, no problem 👍 I have pushed to `feature/winlink-html-forms`. You can rebase your web-forms branch on it now :)

For anyone interested, here is what I did:
```
// Merge your branch
git merge 732f12e

// Rewind one commit
git reset --hard HEAD~

// Patch the code
go mod tidy

// Add the changes and amend
git add go.mod go.sum
git commit --amend --no-edit

// Cherry pick the second commit
git cherry-pick 732f12e
```

**Comment by rainerg2000** [comment]
@martinhpedersen , thank you for the mini git tutorial, I often get myself stuck when I try that kind of thing. 
I rebased rainerg2000:feature/web-forms onto la5nta:feature/winlink-html-forms, and I force-pushed it, so that we can work on the #234 next.

**Pull request closed without merging**
