### PR TITLE
Update PACTOR driver to v2.2.0 (P4 Dragon support)

### PR DESCRIPTION
**Pull request by harenber**
Hi @martinhpedersen ,

thank you very much for your help with Go modules. Here is now the PR which would update the PACTOR driver to v2.2.0, which would support P4 "Dragon" type of Pactor modems.

Related issues: https://github.com/harenber/ptc-go/issues/3, https://github.com/harenber/ptc-go/issues/26 and https://github.com/harenber/ptc-go/issues/29 as well as https://github.com/la5nta/pat/issues/187.

### CODE REVIEW

**Comment by martinhpedersen** [comment]
Torsten, see the Windows build output from AppVeyor statys check. It looks like you're using some code that is not available on Windows, so the code does not comoile on that platform :/

I can investigate closer if you prefer. Just let me know.

Thanks!

**Comment by harenber** [comment]
Oh yes.. the interrupted system call check. I can remove this, this was needed for the other serial library. The one I am using now handles all of that itself. Let me fix that...

**Comment by harenber** [comment]
Hmpff... I somehow get lost with all the versions...

**Comment by harenber** [comment]
Ahhhh.. Go 1.11 doesn't have bytes.ReplaceAll yet :-(

**Comment by harenber** [comment]
@martinhpedersen Please check if this squash was successful. I never did that before, tried with the Sourcetree GUI, hope it did what you wanted.

**Comment by martinhpedersen** [comment]
Torsten, that didn't do it 😅 The goal is to reduce this PR to one commit that contains all the changes.

Try this (in the terminal) on this current branch:
```
// Reset history to first commit, keeping all subsequent changes "staged"
git reset --soft a82386e91c82a967461982dcdc3b400de26f7379

// Amend the "staged" changes to current HEAD
git commit --amend

// Force update the remote branch
git push -f
```

**Pull request merged**
